### ISSUE TITLE
Example of node-red-contrib-arcgis-rest usage?

### ISSUE THREAD

**Issue by johnwalicki** [MetaCEscher/node-red-contrib-arcgis-rest#1]
I'm curious about the node-red-contrib-arcgis-rest Node-RED node.
Is there an example flow (minus the ArcGIS credentials) that I can experiment with?

**Comment by johnwalicki** [comment]
The node-red-contrib-arcgis-rest nodes require a bunch of msg.arcgis.authentication params
What I'm really confused by is the msg.arcgis.updateFeatures.url 
There is likely some common flow pattern to its usage.  An example would be really helpful?

**Comment by ampledata** [comment]
@johnwalicki Hey buddy! Did you make any progress getting this to work?

**Comment by johnwalicki** [comment]
Hey @ampledata  - Great to hear from you.  No one replied to my request for an example.  I was hopeful I could use this Node-RED node in my one of my flows. I never figured out how to use it however. :-(

**Comment by MetaCEscher** [comment]
I'm sorry I missed out on this before. I don't have an example as I no longer use this but if I remember correctly. Authentication shouldn't be required? I  don't remember. You should be setting variables from setting payload function variables.  I will dig through my documents tomorrow at work and reply back

**Comment by ampledata** [comment]
@MetaCEscher Appreciate the follow-up, we've got some fire response folks that want to tie ArcGIS into TAK via: https://github.com/ampledata/node-red-contrib-tak and were hoping to use your nodes to do that.

**Comment by MetaCEscher** [comment]
I posted some examples and fixed a bug but since I haven't used npm in a couple years I messed up and deleted the repo and now can't publish it for 24 hours.  

But in the mean time I made a few examples using ESRI rest services which hopefully clears the air on how to use this

https://github.com/MetaCEscher/node-red-contrib-arcgis-rest/blob/master/examples/examples.json


@ampledata  I don't know what TAK is but I did use this to work with our Fire Department/EMS data from our CAD system. By reading XML files and moving the data to our ArcGIS Server.


@johnwalicki  Sorry I missed your response a year ago. Maybe this will help now though.
